DROP SCHEMA IF EXISTS import CASCADE;
DROP SCHEMA IF EXISTS stage CASCADE;
DROP SCHEMA IF EXISTS dwh CASCADE;
DROP SCHEMA IF EXISTS reporting CASCADE;
CREATE SCHEMA import;
CREATE SCHEMA stage;
CREATE SCHEMA dwh;
CREATE SCHEMA reporting;