create view reporting.patient_maternity as 
SELECT 
v.patient_id,
v.id as visit_no,
v.date_created as visit_date,
a.admission_date, 
c.id as clinic_id,
c."name" as clinic_name,
a.id as admission_id, 
a.admission_ward_id,
w.name as ward_name,
r.first_name ,
r.last_name ,
r.birth_date ,
r.gender as patient_gender,
r.nationality_id ,
m.id as labour_monitoring_id, 
m.bba, 
m.blood_loss_volume, 
m.blood_pressure,
m.cord_normal, 
m.date_created as labour_monitoring_date, 
m.delivery_comments, 
m.delivery_mode, 
m.delivery_time, 
m.drugs_given, 
m.episiotomy, 
m.first_stage_duration, 
m.gravidity, 
m.hours_since_rupture, 
m.induced_labour, 
m.induction_drug_route, 
m.induction_drugs,  
m.membranes_complete, 
m.mother_status, 
m.parity, 
m.patient_admission_id, 
m.perineal_tear, 
m.placenta_complete, 
m.placental_weight, 
m.pulse, 
m.repair, 
m.respiratory_rate, 
m.ruptured_membranes, 
m.second_stage_duration, 
m.temperature, 
m.vaginal_exams_count, 
m.edd, 
m.lmp, 
m.obstetric_care, 
m.obstetric_complication, 
m.pregnancy_history,
n.id as newborn_id, 
n.baby_head_circumference, 
n.baby_height, 
n.baby_status, 
n.baby_weight,   
n.date_created as newborn_date, 
n.description, 
n.first_apgar_score,  
n.patient_labour_monitor_id, 
n.resuscitation, 
n.second_apgar_score, 
n.abdomen_condition, 
n.anus_condition, 
n.back_condition, 
n.chest_condition, 
n.ears_condition, 
n.eyes_condition, 
n.first_name as baby_firstname, 
n.gender as baby_sex, 
n.general_condition, 
n.genitalia_condition, 
n.head_condition, 
n.hip_joints_condition, 
n.last_name as baby_lastname, 
n.lower_limbs_condition, 
n.mouth_condition, 
n.neck_condition, 
n.newborn_complication, 
n.newborn_pmtct, 
n.nose_condition, 
n.other_name, 
n.reflexes_condition, 
n.third_apgar_score, 
n.upper_limbs_condition,
a."comments", 
a.date_created as admission_date_created, 
a.discharge_care_plan, 
a.discharge_date, 
a.discharge_encounter_id, 
a.discharging_doctor_id, 
a.encounter_id, 
e.encounter_notes ,
e.illness_history,
e.date_created as encounter_date,
e.origin ,
a.escorting_nurse_id, 
a.is_closed, 
a.medical_discharge_date, 
a.patient_visit_id, 
a.receiving_nurse_id, 
a.released_by_id, 
a.is_admission_approved
FROM dwh.fact_eafya_labour_monitor m
left join dwh.fact_eafya_newborn n on n.patient_labour_monitor_id = m.id 
inner join dwh.fact_eafya_admissions a on a.id = m.patient_admission_id
inner join dwh.fact_eafya_patient_visit v on v.id = a.patient_visit_id
inner join dwh.fact_eafya_clinic_session s on s.patient_visit_id = v.id 
inner join dwh.dim_eafya_clinic c on c.id = s.clinic_id 
inner join dwh.fact_eafya_encounters e on e.id = a.encounter_id
inner join dwh.dim_eafya_registered_patients r on r.patient_id = v.patient_id 
inner join dwh.dim_eafya_ward w on w.id = a.admission_ward_id
where a.admission_ward_id in (SELECT mapping_id FROM reporting.customizationset where name ilike '%Maternity Ward%' and mapping_id > 0)